baseURL: https://www.chuckhorgan.com/
languageCode: en-us
title: Chuck Horgan
theme: personal-web
copyright: © Chuck Horgan
googleAnalytics: ''
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  accentColor: "#FD3519"
  assets:
    customCSS: ""
    favicon: ""
  breadcrumb: yes
  contact:
    email: "chorgan182@gmail.com"
    text: "Email Me"
  intro:
    main: "Hi, I'm Chuck :wave:"
    sub: "1 Part Data Scientist :man_technologist: <br> 2 Parts Solution Engineer :check_mark:"
  main:
    latestPublishHeader: My Latest Project
  mainSections: portfolio
  notFound:
    gopher: /images/gopher.png
    h1: Bummer!
    p: It seems that this page doesn't exist.
  sections:
    portfolio: project
    post: article
  sidebar:
    backgroundImage: "/images/sdr_res.jpg"
    gradientOverlay: ""
    logo: "/images//Headshot Summer 2021_square.jpg"
  social:
    linkedin: https://www.linkedin.com/in/charles-t-horgan-iv/
    github: https://github.com/chorgan182
    youtube: https://www.youtube.com/channel/UCrbKPkhmPJ7k5Vd8Y1M-d2A
    #facebook: https://www.facebook.com/
    #instagram: https://www.instagram.com/
taxonomies:
  design: designs
  tech: techs
blackfriday:
  hrefTargetBlank: yes
menu:
  main:
    - identifier: about
      name: About
      title: About section
      url: /about/
      weight: -120
    - identifier: portfolio
      name: Portfolio
      title: Portfolio
      url: /portfolio/
      weight: -110
    - identifier: blog
      name: Post
      title: Blog section
      url: /post/
      weight: -100
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
privacy:
  googleAnalytics:
    anonymizeIP: yes
    disable: yes
    respectDoNotTrack: yes
    useSessionStorage: no
  twitter:
    disable: no
    enableDNT: yes
    simple: no
markup:
  goldmark:
    renderer:
      unsafe: yes
